/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarouselText: typeof import('./src/components/CarouselText.vue')['default']
    FormContact: typeof import('./src/components/FormContact.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollCard: typeof import('./src/components/ScrollCard.vue')['default']
    TextCard: typeof import('./src/components/TextCard.vue')['default']
  }
}
